<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_link_length" value="0.1" />
    <xacro:property name="arm_base_link_width" value="0.1" />
    <xacro:property name="arm_base_link_height" value="0.02" />

    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />

    <!-- <link name="base_footprint" /> -->

    <!-- <joint name="dummy_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="arm_base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint> -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_link_length} ${arm_base_link_width} ${arm_base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_link_height / 2.0 }" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_link_length} ${arm_base_link_width} ${arm_base_link_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" x="${arm_base_link_length}" y="${arm_base_link_width}" z="${arm_base_link_height}"
                           o_xyz="0 0 ${arm_base_link_height / 2.0 }" o_rpy="0 0 0" />
    </link>

   <!-- if you want to change the visual the it has to be in visual tags-->
    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${arm_radius}" />
            </geometry>
            <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${arm_length}"
                                o_xyz="0 0 ${arm_length / 2.0}" o_rpy="0 0 0" />
    </link>


    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${arm_radius}" />
            </geometry>
            <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${arm_length}"
                                o_xyz="0 0 ${arm_length / 2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_link_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" velocity="100" effort="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${arm_length + (arm_base_link_height / 2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" velocity="100" effort="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>


</robot>