<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--THIS FILE CONTAINS ALL LINKS AND JOINTS-->

    <!--creating own constant variable or properties-->
    <xacro:property name="base_length"  value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
     <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_footprint" />

    <joint name ="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name ="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />  <!-- creating box & all values are in meter-->
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" /> <!--origin of the box-->
            <material name="blue" />
        </visual>
        <collision>
        <!--same as above because the box is not in contact with ground-->
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />  <!-- creating box & all values are in meter-->
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>
        
        <!--here we have created xacro because it would be same for all box-->
        <!--so no need to write whole code each time-->
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height/2.0}" o_rpy="0 0 0" />
    </link>

    <!--another link-->
    <link name="lidar_link">
        <visual>
            <geometry> 
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                                o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    

    <!--functions in urdf <== xacro:macro-->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />   <!--we want to move wheel 90 deg(1.57 rad) across x-axis-->
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <!--it is easier to define a cylinder as sphere since it is connected to ground-->
                    <!--thus there is only one point of contact with sphere instead of line (cylinder)-->
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                                 o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    
    <!--calling the function <== xacro:macro-->
    <xacro:wheel_link prefix="left" />
    <xacro:wheel_link prefix="right" />

    <link name="castor_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
        <!--since it is already sphere no need to change-->
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius/2.0}"
                              o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <!--link relationship ==> joint-->


    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${base_height + (wheel_length/ 2.0)}" rpy="0 0 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="${-base_length / 4.0} ${base_width/2 + wheel_length/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />  <!--rotation around y axis-->
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />  
        <origin xyz="${-base_length / 4.0} ${-(base_width/2 + wheel_length/2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    
    <joint name="base_castor_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="castor_wheel" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius/2.0}" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint>

    

</robot>