<?xml version= "1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--by adding above url we can add direct variable-->
    <!--Ex.  ${pi/2} instead of 1.57-->

    <!--THIS IS MAIN FILE WHICH CONTAIN TWO XACRO FILE-->
    <!--TO SHORTEN THE CODE WE INCLUDE FILE IN THIS MAIN FILE-->


    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />


    <xacro:include filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="ros2_control.xacro" />
    
    <!--rbotic arm -->
    <!-- <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" /> -->

    <xacro:include filename="camera.xacro" />
    <xacro:include filename="lidar.xacro"/>

    <!-- connecting joints between main robot and robotic arm-->
    <!-- <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 3.0} 0 ${base_height}" rpy="0 0 0" />
    </joint> -->
</robot> 
 